<nav class="navbar navbar-expand-lg shadow-sm" style="backdrop-filter: blur(8px); background-color: rgba(255, 255, 255, 0.75);">
  <div class="container-fluid">
    <a id="header_Home"class="navbar-brand fw-semibold text-dark" href="/Borrow_My_Charger/homeowner_dashboard.php">🏠 Homeowner Panel</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHomeowner" aria-controls="navbarHomeowner" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarHomeowner">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-dark" href="/Borrow_My_Charger/homeowner_dashboard.php">Dashboard</a>
        </li>
     
      
        <li class="nav-item">
          <a class="nav-link text-danger fw-semibold" href="/Borrow_My_Charger/logout.php">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>